[tool.poetry]
name = "telegram-lottery-bot"
version = "1.0.0"
description = "Telegram Lottery Bot"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
